[package]
edition = "2021"
name = "portalbox-vscode"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
cfg-if = "1.0.0"
serde = "1"
serde_json = "1"
xshell = "0.2.1"
