name: Build PortalBox VSCode
on:
  push:
    tags:
      - "v*"
concurrency: 
  group: release
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-11]
        build_arch: [x64]
        # exclude:
        #   - os: windows-2019
        #     build_arch: arm64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.60.0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/setup-python@v2
        with:
          python-version: "2.x"
      - name: Build ${{ matrix.build_arch }} on ${{ matrix.os }}
        env:
          BUILD_ARCH: ${{ matrix.build_arch }}
        run: |
          cargo run
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: portalbox-*.tar.gz